
name: Build Main App (including Unit Tests Run)

on:
  push:
    branches: [ "main", "master", "Development" ]
  pull_request:
    branches: [ "main", "master", "Development"]

jobs:
  build:
    name: Build, test and publish UNIT TEST results to Testmo
    runs-on: ubuntu-latest

    steps:
    - name: Branch Check
      id: branch_check
      run: |
          #use SHA for now, also careful the sha may not be expected, see: https://stackoverflow.com/a/68068674
          echo "release_version=${{ github.sha }}" >> $GITHUB_OUTPUT
          
          ref="${{ github.ref }}"
          if [ "$ref" = "refs/heads/master" ] || [ "$ref" = "refs/heads/main" ]; then
              echo "env_name=Production" >> $GITHUB_OUTPUT
          else
              echo "env_name=Development" >> $GITHUB_OUTPUT
          fi   
          # case "$ref" in
          #   "refs/heads/master" | "refs/heads/main")
          #     echo "env_name=Production" >> $GITHUB_OUTPUT
          #     ;;
          #   "refs/heads/develop")
          #     echo "env_name=Development" >> $GITHUB_OUTPUT
          #     ;;
          #   *)
          #     echo "env_name=Development" >> $GITHUB_OUTPUT
          #     ;;
          # esac
    - name: Environment Selected
      run: echo "Environment will be ${{ steps.branch_check.outputs.env_name }}"
    - uses: actions/checkout@v4
    - name: Setup dotnet8.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore & Build
      run: |
       dotnet restore
       dotnet build --no-restore
    - name: Test and Reporting
      run: |
        RUN_NAME=$(TZ=':Australia/Melbourne' date '+%Y%m%d-%H:%M-API-Unit-Tests')
        npm ci 
        npm install --no-save @testmo/testmo-cli
        npx testmo automation:run:submit \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --name "$RUN_NAME" \
            --source "api-unit-tests" \
            --results **/*unit-test-output.xml \
            -- dotnet test --no-build --verbosity normal --logger:"junit;LogFilePath=unit-test-output.xml" --environment TEST_ENV="${{ steps.branch_check.outputs.env_name }}" --environment TEST_VER="${{ steps.branch_check.outputs.release_version }}"
      env:
        TESTMO_URL: ${{ vars.TESTMO_URL }}
        TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
    - name: Run Selenium Tests (in other repo)
      uses: saragamage/trigger-workflow-and-wait@master
      with:
        owner: ${{ vars.CROSS_REPO_OWNER }}
        repo: ${{ vars.CROSS_REPO_REPO }}
        github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN_PERM_SEL_TEST_PROJ }}
        workflow_file_name: ${{ vars.CROSS_REPO_WF_FILE }}
        ref: main
        wait_interval: 15
        client_payload: '{"env_name": "${{ steps.branch_check.outputs.env_name }}", "release_version": "${{ steps.branch_check.outputs.release_version }}" }'
        propagate_failure: false
        trigger_workflow: true
        wait_workflow: true

    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}
