
name: BUILD-AND-TEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build, test and publish unit test results to Testmo
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test and Reporting
      run: |
        RUN_NAME=$(TZ=':Australia/Melbourne' date '+%Y%m%d-%H:%M-API-Unit-Tests')
        npm ci 
        npm install --no-save @testmo/testmo-cli
        npx testmo automation:run:submit \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --name "$RUN_NAME" \
            --source "api-unit-tests" \
            --results **/*unit-test-output.xml \
            -- dotnet test --no-build --verbosity normal --logger:"junit;LogFilePath=unit-test-output.xml"
      env:
        TESTMO_URL: ${{ vars.TESTMO_URL }}
        TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
    - name: Run Selenium Tests (in other repo)
      uses: saragamage/trigger-workflow-and-wait@master
      with:
        owner: ${{ vars.CROSS_REPO_OWNER }}
        repo: ${{ vars.CROSS_REPO_REPO }}
        github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN_SELENIUM }}
        workflow_file_name: ${{ vars.CROSS_REPO_WF_FILE }}
        ref: main
        wait_interval: 10
        #client_payload: '{}'
        propagate_failure: false
        trigger_workflow: true
        wait_workflow: true
    #uses: SaraGamage/seleniumtestproject/.github/workflows/dotnet.yml@main
